# Generated by Django 4.2.6 on 2023-10-26 14:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('po_no', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=750), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Worker_docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('work_hours', models.IntegerField()),
                ('wages', models.IntegerField(default=0)),
                ('po_no', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='user_docket.supplier')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
